FROM dalibo/buildpack-postgres:bookworm

RUN set -ex; \
    apt-get update -y; \
    apt-get install -y --no-install-recommends \
        gcc \
        libkrb5-dev \
        libreadline-dev \
        pkgconf \
        postgresql-server-dev-15 \
        postgresql-server-dev-14 \
        postgresql-server-dev-13 \
        zlib1g-dev \
    ; \
    apt-get clean; \
    rm -rf /var/lib/apt/lists/* /tmp/* /var/tmp/*; \
    :
